### ISSUE TITLE
"deploy:finalize" hook do not recognise the stage when passed as a command line argument

### ISSUE THREAD

**Issue by marknorrapscm** [mvila/serverless-plugin-scripts#11]
I know this project is in maintenance rather than active development; I am submitting this in the hope that bug fixes are still being implemented.

---

I am using hooks to run a function after I deploy my application.

```
custom:
  scripts:
    hooks:
       "deploy:finalize": serverless invoke -f runAfterDeploy
 ```

I run `serverless deploy` and specify the stage with the `--stage` option. The problem is that the above hook / function call does not seem to recognise whatever it is that I have specified as the stage. If I have set stage using the following `serverless.yml` config so that it uses whatever is supplied via the `--stage` parameter:

```
provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage}
```

...then I get the following error when I deploy using `serverless deploy --stage prod`. The deploy runs correctly and the `prod` value is used everywhere, but the hook does not recognise it and has `undefined` as the value:

![https://i.imgur.com/ruaaA06.png](https://i.imgur.com/ruaaA06.png)

This is a major headache if the `runAfterDeploy` task does something important. Using `${self:opt, "dev"}` instead produces a similar result, whereby no matter what you specify via `--stage` the variable always ends up being `"dev"`.

---

Here's the full re-producible `serverless.yml`:

```
service: serverless-demo

frameworkVersion: "2"

plugins:
  - serverless-offline
  - serverless-plugin-scripts

custom:
  scripts:
    hooks:
       "deploy:finalize": serverless invoke -f runAfterDeploy

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: ${opt:stage}
  environment:
    stage: ${self:provider.stage}

functions:
  runAfterDeploy:
    handler: handler.runAfterDeploy
    events:
      - http:
          path: /runAfterDeploy
          method: get
          cors: true
```
