### ISSUE TITLE
Multiple commands for each hook

### ISSUE THREAD

**Issue by triqi** [mvila/serverless-plugin-scripts#3]
This plugin is very useful, and it would be even more so if we are able to execute multiple commands for each serverless hook.

**Comment by mvila** [comment]
Not tested but I think you can do something like that: `echo First ; echo Then ; echo Finally`

**Comment by triqi** [comment]
I ended up with a single script for each hook, which in turns execute subsequent scripts. This way allows me to control the execution flow, e.g. sync vs. asycn.

Closing.

**Comment by esbenvb** [comment]
I just had the same need and ended up like this:
```yml
  scripts:
    commands:
      update-topic-filters: sls invoke local -f configureSubscriptions --path resources/lambdaTopicFilters.json
      update-queues: sls invoke local -f updateQueues
    hooks:
      before:deploy:finalize: sls update-topic-filters && sls update-queues
  ```

However, I tried doing this (which I think is a much cleaner approach)

```yml
  scripts:
    commands:
      update-topic-filters: sls invoke local -f configureSubscriptions --path resources/lambdaTopicFilters.json
      update-queues: sls invoke local -f updateQueues
    hooks:
      before:deploy:finalize:
        - sls update-topic-filters
        - sls update-queues
  ```

However, this gives me this error
```
  Type Error [ E R R_ I N V A L I D_ A R G_ T Y P E] -----

  The "file" argument must be of type string. Received type object

```

Not sure if it's a limitation of the serverless plugin API or if it could be fixed in the plugin?
