### ISSUE TITLE
Passing ENV variables

### ISSUE THREAD

**Issue by AhmedNourJamalElDin** [mvila/serverless-plugin-scripts#7]
Hello,

In my serverless.yml, there are many env variables that I want to pass to the command that I have defined which is:
```yml
scripts:
    commands:
      nosetests: nosetests
```

so if I run `sls nosetests`, it throws an exception stating that env vars are not defined..
How can I solve it? or is there any other solution to run nosetests with env variables? 

Thanks :D
